export const order = {
  id: '订单号',
  appointment_fee: '已支付',
  appointment_fee_needed: '需交预约金',
  category: '种类',
  color: '颜色',
  data: '时间',
  delivery: '配送方式',
  e_bike_model: '类型',
  expired_date_time: '订单过期时间',
  note: '留言',
  price: '价格',
  reduced_price: '优惠价格',
  rent_deposit: '已交押金',
  rent_deposit_needed: '需要押金',
  rent_time_period: '租用时间',
  serial_number: '车辆编号',
  status: '状态',
  type: '订单类型',
  user: '用户',
};
export const carConstant = {
  battery: '电池',
  category: '类型',
  configure: '配置',
  distance: '续航',
  // introduction: '商品简介',
  name: '名称',
  num_sold: '销量',
  num_view: '浏览量',
  price: '价格',
  type: '类型',
};

